image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CI_BUILD_USER: magnarox
  USER_GITLAB: capgemini
  APP_NAME: insight
  REPO: magnarox/insight

stages:
  - build
  - deploy 

maven-build:
  image: capgemini/insight-build
  stage: build
  script: 
    - npm install
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.war
      - target/*.sh
      - target/Dockerfile

docker-build:
  stage: deploy 
  script:
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN registry.hub.docker.com
    - cd target
    - docker build -t registry.hub.docker.com/$REPO .
    - docker push registry.hub.docker.com/$REPO 
