version: '2'
services:
    insight-app:
        image: insight
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://insight-postgresql:5432/insight
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=insight-elasticsearch:9300
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME=insight
            - SPRING_DATA_JEST_URI=insight-elasticsearch:9200
            - APPLICATION_KIBANA_URI=http://kibana:5601/
        ports:
            - 8080:8080
    insight-postgresql:
        extends:
            file: postgresql.yml
            service: insight-postgresql
    insight-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: insight-elasticsearch
    kibana:
        extends:
            file: elasticsearch.yml
            service: kibana
            