version: '3'
services:
    insight-app:
        image: peploleum/insight:latest
        environment:
        - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=prod,swagger,graphy,reach
        - SPRING_DATA_MONGODB_URI=mongodb://192.168.0.132:27017
        - SPRING_DATA_MONGODB_DATABASE=insight
        - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
        - SPRING_DATA_JEST_URI=http://192.168.0.132:9200
        - APPLICATION_KIBANA_URI=http://192.168.0.132:5601
        - SPRING_DATA_GREMLIN_ENDPOINT=192.168.0.132
        - SPRING_DATA_GREMLIN_PORT=8182
        - SPRING_DATA_GREMLIN_SSL_ENABLED=false
        - SPRING_DATA_GREMLIN_TELEMETRY_ALLOWED=false
        - SPRING_DATA_GREMLIN_USERNAME=capgemini
        - SPRING_DATA_GREMLIN_PASSWORD=root
        ports:
        - 8080:8080
        networks:
        - insight
networks:
    insight:
        driver: bridge
